version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - "8080"
    links:
      - mongo
      - redis
    environment:
      - MONGOURI=mongodb://mongo:27017/devchallenge
      - REDISURI=redis://redis/1
    volumes:
      - local_storage:/app/local_storage

  mongo:
    image: mongo:3.6.4-jessie
    restart: always
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    volumes:
      - "/data"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  local_storage: